name: Test Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Create necessary directories
      run: |
        mkdir -p uploads results
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create test environment file
      run: |
        echo "GEMINI_API_KEY=test_key_for_ci" > .env
        echo "FLASK_ENV=testing" >> .env
        
    - name: Test application structure
      run: |
        python -c "
        import sys
        import os
        sys.path.append('src')
        
        # Test basic imports
        print('Testing imports...')
        
        try:
            from src.utils.config import Config
            print('✅ Config module imports successfully')
        except Exception as e:
            print(f'⚠️ Config import warning (expected in CI): {e}')
        
        try:
            import app
            print('✅ Flask app imports successfully')
            print('✅ All tests passed!')
        except Exception as e:
            print(f'❌ App import failed: {e}')
            raise
        "
        
    - name: Test WSGI entry point
      run: |
        python -c "
        try:
            import wsgi
            print('✅ WSGI entry point imports successfully')
        except Exception as e:
            print(f'❌ WSGI import failed: {e}')
            raise
        "
        
    - name: Validate project structure
      run: |
        echo "Checking project structure..."
        ls -la
        echo "Templates directory:"
        ls -la templates/
        echo "Static directory (if exists):"
        ls -la static/ || echo "No static directory found"
        echo "Source directory:"
        ls -la src/
        echo "✅ Project structure validation complete"
